name: CI Pipeline

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build backend
      run: docker build -t backend ./backend

    - name: Run tests
      run: docker run backend pytest

    - name: Trivy Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: backend
