name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout code
    - name: Checkout code
      uses: actions/checkout@v4

    # 2️⃣ Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # 3️⃣ Login to Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # 4️⃣ Build backend image
    - name: Build backend image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest ./backend

    # 5️⃣ Run backend tests
    - name: Run backend tests
      run: |
        docker run --rm ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest pytest || true

    # 6️⃣ Trivy scan (backend)
    - name: Trivy Scan - Backend
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest
        severity: CRITICAL,HIGH

    # 7️⃣ Push backend image
    - name: Push backend image
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest

    # 8️⃣ Build frontend image
    - name: Build frontend image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest ./frontend

    # 9️⃣ Trivy scan (frontend)
    - name: Trivy Scan - Frontend
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
        severity: CRITICAL,HIGH

    # 🔟 Push frontend image
    - name: Push frontend image
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
